"""empty message

Revision ID: d8676d228162
Revises: 168e757265b9
Create Date: 2025-03-16 09:51:04.219207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8676d228162'
down_revision = '168e757265b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('maintenance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('housekeeper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('housekeeper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('maintenance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
